Mill_Sinumerik840D
SprutCAMTech/SprutCAM-postprocessors-examples pull request #9
Opened 2022-07-22 14:04 UTC by TerrOFGod

Трофимчук Всеволод закончил формирование всех основных методов. Старался делать наиболее изменяемую программу прибегая к данным из полей cmd там где не понимал откуда берутся данные в старом постпроцессоре брал cld, ptr, flt. Подробнее о процессе разработки в комитах.

2022-07-25 20:56 UTC, SprutCAMTech requested changes
1. Постпроцессор не компилируется.
// не компилируется здесь
Postprocessor.cs SetAxisValues()
cycle.XT_ = X.v; cycle.State.YT_ = Y.v; cycle.State.ZT_ = Z.v;
// видимо имелось в виду
cycle.State.XT_ = X.v;...
Переменные XT_, YT_, ZT_ в принципе можно вообще вынести за пределы класса цикла и объявить в самом постпроцессоре как 
public TInp3DPoint LastPnt;

2. Выдается предупреждение компилятора.
Postprocessor.cs
	"code": "CS0168",
	"message": "Переменная \"i\" объявлена, но ни разу не использована. [Sinumerik (840D)_Mill_DN]",
	"startLineNumber": 649,
	"startColumn": 17,

3. В обработчике OnFrom() старое значение v0 регистров сбрасывается. Значения всех координат берутся из cld[1].
Это приводит к обязательному выводу осей XYZ в первом перемещении. 
Это некорректно. Предполагается что в момент начала обработки инструмент уже находится в некоторой начальной точке, которую выводить в программу не нужно. 
Команда From как раз задает эту начальную точку траектории.
nc.X.v = cld[1]; nc.X.v0 = double.MaxValue;
следует просто заменить на 
nc.X.Hide(cld[1]);

4. Регистр нумерации кадров лучше определить как
        public CountingNCWord BlockN = new CountingNCWord("N{####}", 10, 10, 1);
Внутри класса CountingNCWord уже реализована логика увелиения на заданный шаг (10) и автоматический сброс до начального значения в случае превышения разрядности. Тогда процедура ResetCounting() уже не нужна. Увеличивать значение регистра можно так
   nc.BlockN.v += nc.BlockN.AutoIncrementStep;
Лучше даже оформить данную строку в виде Extension-метода AddStep() для класса CountingNCWord(), т.к. в нескольких местах повторяется. Тогда можно будет написать как-то так
   nc.BlockN.AddStep();

5. Во многих случаях вместо явного присвоения разных значений v и v0 регистров
    X.v = axis.Value;
    X.v0 = double.MaxValue;
можно использовать методы X.Show(), X.Show(cld[1]), X.Hide(), X.Hide(123), X.Reset(), X.Reset(axis.Value) и т.п. в зависимости от потребностей в каждом случае.

6. Обработчик OnPPFun() для ветки 'case 58' это то же самое что OnStartTechOperation(), 
  для ветки 'case 59' - OnFinishTechOperation. Лучше перенести код в них.

7. Многие числовые переменные типа IsFirstCycle и др. можно заменить на флаги bool.

8. Оба обработчика OnStop() и OnOpStop() выводят "M01", хотя первый должен выводить "M00".
9.  Можно попробовать реализовать работу с подпрограммами.
Лекция по реализации подпрограмм в новых постпроцессорах на примере стойки Heidenhain есть тут. С 30-й минуты.
https://youtu.be/R0MN8RL0kgo

2022-07-29 13:07 UTC, TerrOFGod commented
Можно уточнить?

2022-07-29 13:10 UTC, TerrOFGod commented
В старом коде постпроцессора использовалось создание двух типов файлов .mpf и .spf. Я могу предположить как это происходило, но в версии .net нет таких расширений есть .nc. Вопрос: Как реализовывать смену файлов?

2022-07-29 16:04 UTC, TerrOFGod commented
сделал почти все не могу доделать M8

2022-08-01 08:57 UTC, TerrOFGod commented
Сделал полностью рабочую версию для подпрограмм

2022-08-05 07:47 UTC, SprutCAMTech approved these changes

2023-02-04 20:31 UTC, merged